---
- name: Send email with Ansible
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Send notification email
      mail:
        host: smtp.gmail.com
        port: 587                     # Correct port for STARTTLS
        username: gptishh@gmail.com
        password: "dqzh drfi thmr mxxm"  # Assuming this is your app password
        to: commanderata@gmail.com
        subject: 'Ansible Notification'
        body: 'This is a test email sent by Ansible.'
        sender: gptishh@gmail.com
        secure: starttls               # Correct security option for STARTTLS
        headers:
          - X-Priority: '2'
      delegate_to: localhost
